var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
import { prisma } from "../lib/prisma";
export const createBilling = (req, res) => __awaiter(void 0, void 0, void 0, function* () {
    try {
        const { billingId, customerId, totalAmount, items } = req.body;
        if (!customerId || !totalAmount || !items || !Array.isArray(items)) {
            return res.status(400).json({
                message: "customerId, totalAmount, and items array are required",
            });
        }
        if (items.length === 0) {
            return res.status(400).json({
                message: "At least one item is required",
            });
        }
        // Validate customer exists
        const customer = yield prisma.customer.findUnique({
            where: { customerId: String(customerId) },
        });
        if (!customer) {
            return res.status(404).json({ message: "Customer not found" });
        }
        // Validate all products exist and have sufficient stock
        const productIds = items.map((item) => item.productId);
        const products = yield prisma.products.findMany({
            where: {
                productId: { in: productIds },
            },
        });
        if (products.length !== productIds.length) {
            return res.status(400).json({ message: "One or more products not found" });
        }
        // Check stock availability
        for (const item of items) {
            const product = products.find((p) => p.productId === item.productId);
            if (!product) {
                return res.status(400).json({
                    message: `Product ${item.productId} not found`,
                });
            }
            if (product.stockQuantity < item.quantity) {
                return res.status(400).json({
                    message: `Insufficient stock for product ${product.name}. Available: ${product.stockQuantity}, Requested: ${item.quantity}`,
                });
            }
        }
        // Create billing with items and update stock in a transaction
        const result = yield prisma.$transaction((tx) => __awaiter(void 0, void 0, void 0, function* () {
            // Create billing (billingId will be auto-generated if not provided)
            const billing = yield tx.billing.create({
                data: Object.assign(Object.assign({}, (billingId && { billingId })), { customerId,
                    totalAmount }),
            });
            // Create billing items and update product stock
            const billingItems = yield Promise.all(items.map((item) => __awaiter(void 0, void 0, void 0, function* () {
                const subtotal = item.quantity * item.price;
                // Update product stock
                yield tx.products.update({
                    where: { productId: item.productId },
                    data: {
                        stockQuantity: {
                            decrement: item.quantity,
                        },
                    },
                });
                // Create billing item (billingItemId will be auto-generated by UUID default)
                return yield tx.billingItem.create({
                    data: {
                        billingId,
                        productId: item.productId,
                        quantity: item.quantity,
                        price: item.price,
                        subtotal,
                    },
                    include: {
                        product: true,
                    },
                });
            })));
            // Return billing with items and customer
            return yield tx.billing.findUnique({
                where: { billingId },
                include: {
                    customer: true,
                    BillingItem: {
                        include: {
                            product: true,
                        },
                    },
                },
            });
        }));
        res.status(201).json(result);
    }
    catch (error) {
        if (error.code === "P2002") {
            return res.status(400).json({ message: "Billing ID already exists" });
        }
        console.error("Error creating billing:", error);
        res.status(500).json({ message: "Error Creating Billing" });
    }
});
export const getBillings = (req, res) => __awaiter(void 0, void 0, void 0, function* () {
    try {
        const billings = yield prisma.billing.findMany({
            include: {
                customer: true,
                BillingItem: {
                    include: {
                        product: true,
                    },
                },
            },
            orderBy: {
                timestamp: "desc",
            },
        });
        res.json(billings);
    }
    catch (error) {
        res.status(500).json({ message: "Error Retrieving Billings" });
    }
});
export const getBillingById = (req, res) => __awaiter(void 0, void 0, void 0, function* () {
    try {
        const { billingId } = req.params;
        const billing = yield prisma.billing.findUnique({
            where: { billingId: String(billingId) },
            include: {
                customer: true,
                BillingItem: {
                    include: {
                        product: true,
                    },
                },
            },
        });
        if (!billing) {
            return res.status(404).json({ message: "Billing not found" });
        }
        res.json(billing);
    }
    catch (error) {
        res.status(500).json({ message: "Error Retrieving Billing" });
    }
});
